version: 2

sources:
  - name: raw
    database: ecommerce_db
    schema: raw
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products
      - name: payments
      - name: reviews

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
